frontend:
  image: lyzhang1999/frontend
  tag: 'latest'
  autoscaling:
    averageUtilization: 90

backend:
  image: registry.cn-hangzhou.aliyuncs.com/dongjun11/flask-demo
  tag: 'v0.1.2'
  autoscaling:
    averageUtilization: 90

database:
  enabledPostgre: true  # 是否部署集群内部的数据库
  uri: pg-service
  username: "admin"
  password: "zdj7900802"

postgre:
  adminUser: "admin"  # 数据库管理员账户
  adminPassword: "zdj7900802"  # 数据库管理员密码
